language: c
install:
   - sudo apt-get update && sudo apt-get install -y build-essential libx11-dev libxinerama-dev sharutils libxcb-icccm4-dev libxcb1-dev libxcb-keysyms1-dev
compiler:
     - clang
     - gcc
script:  make

